### ISSUE TITLE
Fix player spawning in invalid locations

### ISSUE THREAD

**Issue by muzikbike** [OpenCubicChunks/CubicChunks2#13]
Incredibly minor and far from being a priority to look at, but players should only be allowed to spawn in on #minecraft:valid_sapwn blocks, which are not obstructed by anything solid. Despite this, the player often spawns inside of leaves:

![2020-07-26_16 03 30](https://user-images.githubusercontent.com/52297970/88482554-e3da6080-cf59-11ea-8d90-e94cf9629d78.png)

**Comment by NotStirred** [comment]
closed by #87
