### ISSUE TITLE
Server w/ Cubic Chunks eats all memory and dies

### ISSUE THREAD

**Issue by imreallybadatnames** [OpenCubicChunks/CubicChunks2#68]
Environment:
1. 1.17.1 fabric server, loader version 0.11.7
2. mods:
    - fabric api 0.41.3
    - cubic chunks 1.17.1-0.0.667.0-SNAPSHOT, compiled from latest commit at default branch
3. Java 17
4. JVM args: `-Xmx24G -XX:+UseZGC`

A server with all default settings and nothing but Cubic Chunks and fabric API eventually consumes all memory given and dies from out of memory exception/oom kill.

With no mods except cubic chunks and fabric api, with all default settings, it either generates the world in several minutes then idles at 12 gb usage, or crash from no memory during generation.
Example of idling:
![2021-11-02_12-02](https://user-images.githubusercontent.com/68000899/139770698-8bf62831-ceae-4eb7-84ff-1496e5ff9cd3.png)

Example of last moments before OOM crash:
![2021-11-02_12-05](https://user-images.githubusercontent.com/68000899/139770741-a10fe489-f878-405d-99b0-f2a2af5bf7a3.png)

logs for server OOM killed on generation:
[latest.log](https://github.com/OpenCubicChunks/CubicChunks2/files/7457102/latest.log)

**Comment by imreallybadatnames** [comment]
sometimes it does generate beyond 0%, but its very rare if it fully prepares world spawn and then goes to idle.

**Comment by CorgiTaco** [comment]
1.17 CC is not at all ready to use for 1.17. **Please don't open issues for a very very unpolished project**.
