### ISSUE TITLE
Lang keys not translating in dev env

### ISSUE THREAD

**Issue by CursedFlames** [OpenCubicChunks/CubicChunks2#81]
Lang keys appear untranslated in dev, whereas they display correctly outside of dev. We don't use any other assets, so it's not clear whether this issue extends to other assets as well. Not sure what's causing this; possibly an issue with our gradle setup.

**Comment by NotStirred** [comment]
closed by https://github.com/OpenCubicChunks/CubicChunks2/commit/ba25b819541dc2030961c4302d43727678ffc74b
